=== C3BI-pasteur-fr/common-workflow-language/schemas/tool.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id" : "https://raw.githubusercontent.com/common-workflow-language/common-workflow-language/draft-1/schemas/tool.json",
    "description": "Common tool description schema",
    "type": "object",
    "definitions": {
        "expression": {
            "type": "object",
            "required": ["$expr"],
            "properties": {
                "$expr": {
                    "type": "string"
                }
            }
        },
        "template": {
            "type": "object",
            "required": ["$tmpl"],
            "properties": {
                "$tmpl": {
                    "type": "string"
                }
            }
        },
        "strOrExpr": {
            "oneOf": [
                { "type": "string" },
                { "$ref": "#definitions/expression" },
                { "$ref": "#definitions/template" },

                { "$ref": "https://raw.githubusercontent.com/common-workflow-language/common-workflow-language/draft-1/schemas/metaschema.json#definitions/$job" }
            ]
        },
        "numOrExpr": {
            "oneOf": [
                { "type": "number" },
                { "$ref": "#definitions/expression" },
                { "$ref": "https://raw.githubusercontent.com/common-workflow-language/common-workflow-language/draft-1/schemas/metaschema.json#definitions/$job" }
            ]
        },
        "intOrExpr": {
            "oneOf": [
                { "type": "integer" },
                { "$ref": "#definitions/expression" },
                { "$ref": "https://raw.githubusercontent.com/common-workflow-language/common-workflow-language/draft-1/schemas/metaschema.json#definitions/$job" }
            ]
        },
        "boolOrExpr": {
            "oneOf": [
                { "type": "boolean" },
                { "$ref": "#definitions/expression" },
                { "$ref": "https://raw.githubusercontent.com/common-workflow-language/common-workflow-language/draft-1/schemas/metaschema.json#definitions/$job" }
            ]
        }
    },
    "properties": {
        "documentAuthor": {
                    "oneOf": [
                        { "$ref": "https://raw.githubusercontent.com/common-workflow-language/common-workflow-language/draft-1/schemas/metaschema.json#definitions/stringArray" },
                        { "type": "string" }
                    ]
        },
        "documentDescription": { "type": "string" },
        "softwareDescription": { "type": "object" },
        "softwareRelease": { "type": "object" },
        "inputs": { "$ref": "https://raw.githubusercontent.com/common-workflow-language/common-workflow-language/draft-1/schemas/metaschema.json" },
        "outputs": { "$ref": "https://raw.githubusercontent.com/common-workflow-language/common-workflow-language/draft-1/schemas/metaschema.json" },
        "requirements": {
            "type": "object",
            "properties": {
                "platformFeatures": { "$ref": "https://raw.githubusercontent.com/common-workflow-language/common-workflow-language/draft-1/schemas/metaschema.json#definitions/stringArray" },
                "environment": {
                    "type": "object",
                    "properties": {
                        "container": {
                            "type": "object",
                            "properties": {
                                "imageId": { "type": "string" },
                                "type": { "type": "string" },
                                "uri": { "type": "string" }
                            }
                        }
                    }
                },
                "resources": {
                    "type": "object",
                    "properties": {
                        "cpu": { "$ref": "#definitions/intOrExpr" },
                        "diskSpace": { "$ref": "#definitions/intOrExpr" },
                        "mem": { "$ref": "#definitions/intOrExpr" },
                        "network": { "$ref": "#definitions/boolOrExpr" }
                    }
                },
                "templates": {
                    "type":"array",
                    "items": {
                        "type":"object",
                        "properties": {
                            "name": {"$ref": "#definitions/strOrExpr"},
                            "value": {"$ref": "#definitions/strOrExpr"}
                        }
                    }
                }

            }
        },
        "adapter": {
            "type": "object",
            "properties": {
                "args": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "prefix": { "type": "string" },
                            "order": { "type": "integer" },
                            "separator": { "type": "string" },
                            "itemSeparator": { "type": "string" },
                            "value": { "$ref": "#definitions/strOrExpr" }
                        }
                    }
                },
                "baseCmd": {
                    "oneOf": [
                        {
                            "type": "array",
                            "items": {
                                "oneOf": [
                                    {"type": "string"},
                                    {"$ref": "#definitions/expression"},
                                    {"$ref": "#definitions/template"}
                                ]
                            },
                            "minItems": 1,
                            "uniqueItems": false
                        },
                        { "type": "string" },
                        { "$ref": "#definitions/expression" },
                        { "$ref": "#definitions/template" }
                    ]
                },
                "stdout": { "$ref": "#definitions/strOrExpr" },
                "stdin": { "$ref": "#definitions/strOrExpr" }
            }
        }
    }
}

=== C3BI-pasteur-fr/common-workflow-language/examples/sort-tool.json
{
    "documentAuthor": ["peter.amstutz@curoverse.com"],
    "documentDescription": "Sort the contents of a file to stdout using 'sort' running in a docker container.",
    "requirements": {
        "environment": {
            "container": {
                "type": "docker",
                "imageId": "arvados/jobs"
            }
        }
    },
    "inputs": {
        "type": "object",
        "required": [ "file1" ],
        "properties": {
            "file1": {
                "type": "file",
                "adapter": {
                    "order": 1
                }
            }
        }
    },
    "adapter": {
        "baseCmd": "sort",
        "stdout":"sorted.txt"
    }
}

=== C3BI-pasteur-fr/common-workflow-language/examples/cat3-tool.json
{
    "documentAuthor": ["peter.amstutz@curoverse.com"],
    "documentDescription": "Copy the contents of a file to 'output.txt' using 'cat' running in a docker container.",
    "requirements": {
        "environment": {
            "container": {
                "type": "docker",
                "imageId": "arvados/jobs"
            }
        }
    },
    "inputs": {
        "type": "object",
        "required": [ "file1" ],
        "properties": {
            "file1": {
                "type": "file",
                "adapter": {
                    "order": 1
                }
            }
        }
    },
    "outputs": {
        "type": "object",
        "required": [ "output" ],
        "properties":{
            "output": {
                "adapter": {
                    "glob":"output.txt"
                }
            }
        }
    },
    "adapter": {
        "baseCmd": "cat",
        "stdout": "output.txt"
    }
}

=== C3BI-pasteur-fr/common-workflow-language/examples/cat4-tool.json
{
    "documentAuthor": ["peter.amstutz@curoverse.com"],
    "documentDescription": "Copy the contents of a file by piping it into stdin of 'cat' and redirecting to 'output.txt' running in a docker container.",
    "requirements": {
        "environment": {
            "container": {
                "type": "docker",
                "imageId": "arvados/jobs"
            }
        }
    },
    "inputs": {
        "type": "object",
        "required": [ "file1" ],
        "properties": {
            "file1": {
                "type": "file"
            }
        }
    },
    "outputs": {
        "type": "object",
        "required": [ "output" ],
        "properties":{
            "output": {
                "adapter": {
                    "glob":"output.txt"
                }
            }
        }
    },
    "adapter": {
        "baseCmd": "cat",
        "stdin": {"$job": "#inputs/file1/path"},
        "stdout": "output.txt"
    }
}

=== C3BI-pasteur-fr/common-workflow-language/examples/rev-tool.json
{
    "documentAuthor": ["peter.amstutz@curoverse.com"],
    "documentDescription": "Reverse the contents of a file to stdout using 'rev' running in a docker container.",
    "requirements": {
        "environment": {
            "container": {
                "type": "docker",
                "imageId": "arvados/jobs"
            }
        }
    },
    "inputs": {
        "type": "object",
        "required": [ "file1" ],
        "properties": {
            "file1": {
                "type": "file",
                "adapter": {
                    "order": 1
                }
            }
        }
    },
    "outputs": {
        "type": "object",
        "required": [ "output" ],
        "properties":{
            "output": {
                "adapter": {
                    "glob":"reversed.txt"
                }
            }
        }
    },
    "adapter": {
        "baseCmd": "rev",
        "stdout":"reversed.txt"
    }
}
